services:
  web:
    build: .
    container_name: geeks_web
    command: ./entrypoint.sh
    env_file:
      - .env
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    container_name: geeks_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: geeks_redis
    volumes:
      - redis_data:/data

  celery:
    build: .
    container_name: geeks_celery
    command: celery -A core worker -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    container_name: geeks_celery_beat
    command: celery -A core beat -l info
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: geeks_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis_data:
